<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class LoadPerformance extends Model
{
    use SoftDeletes;
    protected $table = 'load_performances';
    protected $primaryKey = 'tms_id';
    public $incrementing = false;
    protected $fillable = [
        'tms_id',
        'created_date',
        'carrier_reference',
        'carrier_name',
        'equipment_description',
        'vehicle_number',
        'driver_name',
        'shipment_reference',
        'load_status',
        'first_pick_location_name',
        'last_drop_location_name',
        'first_pick_original_plan_date_start',
        'first_pick_appt_end_date',
        'last_drop_original_plan_date_start',
        'last_drop_appt_end_date',
        'routing_guide_name',
        'payable_total_base_rate',
        'payable_total_accessorials',
        'payable_total_rate',
        'billable_total_rate',
        'closed_date',
        'websettle_batch_status',
        'websettle_batch_transmit_date',
        'trailer_number',
        'weight_lb',
        'weight_kg',
        'void_date',
        'transportation_mode',
        'tour_id',
        'total_distance_km',
        'shipper_load_number',
        'routing_guide_first_carrier_carrier_reference',
        'routing_guide',
        'routed_date_used',
        'required_equipment_short_description',
        'required_equipment',
        'related_order_identifiers',
        'purchase_price',
        'profit_or_loss_pct',
        'priority',
        'pieces_sum',
        'pieces_max',
        'pieces',
        'matched_routing_guide',
        'load_websettle_hold_status',
        'load_reference_numbers',
        'load_profit_loss_amount',
        'load_group',
        'load_contact',
        'linear_space_m',
        'linear_space_ft',
        'last_drop_original_plan_date_end',
        'last_drop_location_reference_number',
        'last_drop_location_city',
        'last_drop_has_pod',
        'last_drop_calculated_date',
        'last_drop_arrival_date',
        'intermediate_stops',
        'first_routing_guide_carrier_base_rate',
        'first_pick_original_plan_date_end',
        'first_pick_location_reference_number',
        'first_pick_location_city',
        'first_pick_has_pod',
        'first_pick_eta_date',
        'first_pick_departure_date',
        'first_pick_calculated_due_date_indicator',
        'first_pick_calculated_date',
        'first_pick_appt_start_date',
        'first_pick_appt_scheduled_date',
        'first_pick_appointment_requested_date',
        'division',
        'data_mart_update_date',
        'carrier_rank_when_tendered',
        'first_pick_appointment_confirmed_date',
        'last_drop_eta_date',
        'last_drop_departure_date',
        'websettle_batch_name',
        'carrier_rate_modified',
        'carrier_vendor_number',
        'creation_process',
        'driver_name2',
        'execution_plan_rank',
        'customer_reference',
        'customer_name',
    ];
}
